framework:
    rate_limiter:
        login:
            policy: 'fixed_window'
            limit: 5
            interval: '15 minutes'
        
        password_reset:
            policy: 'fixed_window'
            limit: 3
            interval: '1 hour'
        
        api:
            policy: 'fixed_window'
            limit: 100
            interval: '1 minute'

